name: xrlint
channels:
  - conda-forge
dependencies:
  - python >=3.10
  # Library Dependencies
  - click
  - fsspec
  - pyyaml
  - tabulate
  - xarray
  # Dev Dependencies
  - mkdocs
  - mkdocs-autorefs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - pytest
  - pytest-cov
  - requests-mock
  - ruff
  # Testing Datasets
  - dask
  - pandas
  - netcdf4
  - numpy
  # actually zarr >=2.18,<3.0 | >=3.0.2
  - zarr
