name: xrlint
channels:
  - conda-forge
dependencies:
  - python >=3.10
  # Library Dependencies
  - click
  - fsspec
  - pyaml
  - tabulate
  - xarray
  # Dev Dependencies
  - black
  - flake8
  - jupyterlab
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - pytest
  - pytest-cov
  - requests-mock
  # Testing Datasets
  - pandas
  - netcdf4
  - numpy
  - zarr
