DEFAULT_OUTPUT_FORMAT = "simple"
DEFAULT_MAX_WARNINGS = -1

CONFIG_EXTENSIONS = ".yml", ".yaml", ".json", ".py"

DEFAULT_CONFIG_BASENAME = "xrlintrc"
DEFAULT_CONFIG_FILENAMES = [
    f".{DEFAULT_CONFIG_BASENAME}{ext}" for ext in CONFIG_EXTENSIONS
]
