CONFIG_EXTENSIONS = ".yml", ".yaml", ".json", ".py"

DEFAULT_CONFIG_BASENAME = "xrlint.config"
DEFAULT_CONFIG_FILENAMES = [
    f"{DEFAULT_CONFIG_BASENAME}.py",
    f"{DEFAULT_CONFIG_BASENAME}.yaml",
    f"{DEFAULT_CONFIG_BASENAME}.json",
]

DEFAULT_OUTPUT_FORMAT = "simple"
DEFAULT_MAX_WARNINGS = 5
